apiVersion: v1
kind: Namespace
metadata:
  name: sosivio
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sosivio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.sosivio.io
    targetRevision: HEAD
    path: sosivio/sosivio
    helm:
      values: []
      parameters:
        - name: platform
          value: eks
  destination:
    server: https://kubernetes.default.svc
    namespace: sosivio
  syncPolicy:
    automated: {}
