apiVersion: v1
kind: Namespace
metadata:
  name: sosivio
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sosivio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.sosivio.io
    targetRevision: HEAD
    path: sosivio/sosivio
  destination:
    server: https://kubernetes.default.svc
    namespace: sosivio
  syncPolicy:
    automated: {}
  # Define the parameters for Helm
  # These will be passed to the `helm install` command
  # using the `--set` flag
  helm:
    # Values passed here will be available to the chart as {{ .Values.platform }}
    valueFiles: []
    parameters:
      - name: platform
        value: eks
