## this config will work because it doesn't have the latest tag
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginxdeployment
  replicas: 2
  template:
    metadata:
      labels:
        app: nginxdeployment
    spec:
      containers:
      - name: nginxdeployment
        image: nginx:1.23.1 # using "latest" image tag instead of a specific version will not work after we have applied constraint configs
        ports:
        - containerPort: 80