apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sosivio
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sosivio
  source:
    repoURL: 'https://helm.sosiv.io'
    targetRevision: sosivio/sosivio
    helm:
      parameters:
        - name: platform
          value: eks
  project: default 
