name: 'prodVPC Destroy Terraform'

on:
    workflow_dispatch:

#on:
    #push:
        #branches: ["main"]
    #pull_request:

permissions:
    contents: read

jobs: 
    terraform:
        name: 'Terraform'
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                shell: bash

        steps: 
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          working-directory: infrastructure-plan/aws-vpc/production/
          run: terraform init -backend-config "bucket=aws-terra-s3" -backend-config "key=aws-terraform-vpc.tfstate"
 
        # - name: Terraform Workspace
        #   working-directory: plan/vpc/production/
        #   run: terraform workspace new prod-vpc || terraform workspace select prod-vpc
          
        - name: Terraform Format
          working-directory: infrastructure-plan/aws-vpc/production/
          run: terraform fmt

        - name: Terraform Plan
          working-directory: infrastructure-plan/aws-vpc/production/
          run: terraform plan
    
        - name: Terraform apply
          working-directory: infrastructure-plan/aws-vpc/production/
          run: terraform destroy -auto-approve  
              
          
