name: 'prod-vpc Apply Terraform'

on:
    workflow_dispatch:
        branches: ["main", "development", "staging", "production"]

#on:
    #push:
        #branches: ["main"]
    #pull_request:

permissions:
    contents: read

jobs: 
    terraform:
        name: 'Terraform'
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                shell: bash

        steps: 
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Copy .env file to the working directory
          run: cp .env infrastructure-plan/aws-vpc/

        - name: Terraform Init
          working-directory: infrastructure-plan/aws-vpc/
          run: |
            terraform init \
              -backend-config="bucket=${{ vars.AWS_S3_BUCKET }}" \
              -backend-config="region=${{ vars.AWS_REGION }}"
 
        # - name: Terraform Workspace
        #   working-directory:
        #   run: terraform workspace new prod-vpc || terraform workspace select prod-vpc
          
        - name: Terraform Format
          working-directory: infrastructure-plan/aws-vpc/
          run: terraform fmt

        - name: Terraform Plan
          working-directory: infrastructure-plan/aws-vpc/
          run: terraform plan
    
        - name: Terraform apply
          working-directory: infrastructure-plan/aws-vpc/
          run: terraform apply -auto-approve  
              
          

