name: 'prod-vpc-apply-terraform'

on:
    workflow_dispatch:

#on:
    #push:
        #branches: ["main"]
    #pull_request:

permissions:
    contents: read

jobs: 
    terraform:
        name: 'Terraform'
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                shell: bash

        steps: 
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          working-directory: plan/vpc/production/
          run: terraform init -backend-config "bucket=myterraformbucket12" -backend-config "key=eks-prod.tfstate"
              #terraform workspace new dev || terraform workspace select dev

        - name: Terraform Format
          working-directory: plan/vpc/production/
          run: terraform fmt

        - name: Terraform Plan
          working-directory: plan/vpc/production/
          run: terraform plan -var="k8sVersion=1.27"
    
        - name: Terraform apply
          working-directory: plan/vpc/production/
          run: terraform apply -var="k8sVersion=1.27" -auto-approve  
              
          

